### ISSUE TITLE
feature request: delete version

### ISSUE THREAD

**Issue by fyangd** [devigned/pub#26]
Currently, the `versions` subcommand only supports putting a version.  However, I'd like to be able to delete a version from a draft plan.

A future thought may be to also request deletion of a version from a live/published plan.  Although reading the Azure documentation, it's not clear to me if this is supported via the exposed marketplace API.

**Comment by devigned** [comment]
@marosset & @CecileRobertMichon do you recall the steps for deleting a live version from a plan?

The fact that it is missing from the CLI is notable. The "right" way to delete a version was not completely clear to me, so I avoided destructive operations.

Are you running into a limitation with the number of versions you'd like to publish? Can you provide a bit of background on what you are doing?

**Comment by marosset** [comment]
I don't recall seeing any guidance on deleting a version from a live plan (and personally would be a bit scared to do so).

For deleting a version from a draft plan I *think* you can just query, remove the version, the PUT the whole plan with the versions removed.

@devigned Is there a way to delete a draft plan? 
that might work better.

**Comment by devigned** [comment]
> For deleting a version from a draft plan I think you can just query, remove the version, the PUT the whole plan with the versions removed.

@marosset, yep. That was what I was thinking too. I just haven't tested it out.

**Comment by fyangd** [comment]
@devigned @marosset Thanks for promptly responding to my issue!

For now, I'm requesting to remove versions only from draft plans, and I'd have gone about it just the way that @marosset described.  

Deleting versions from draft plan is important to us, because we build images daily but only publish weekly.   So, I'd like to be able to keep only the most recent version of a plan by deleting all prior versions before publishing it.

Once a plan goes live, I read in the [documentation](https://docs.microsoft.com/en-us/azure/marketplace/azure-vm-create-plans) that

> After an image has been published, you can't edit it, but you can delete it. Deleting a version prevents both new and existing users from deploying a new instance of the deleted version.

This seems to me more like a manual delisting operation than a `deletion` API.  Deleting versions from a live plan is secondary, but I'm just trying to understand if this can be automated or not.  

I also realized that this project is fairly small and probably not people's main focus.  So I'd be happy to contribute if others lack the bandwidth.

Finally, thank you building and maintaining the project!

**Comment by devigned** [comment]
@fyangd I'd be delighted to pull in a contribution for deleting draft plans, and thank you for offering to contribute that change.

I can't offer much help on the implementation for the next week or so, but I can offer to pull in a contact from the publishing team or at a minimum relay questions about the behavior of the API if they arise.

**Comment by fyangd** [comment]
Going to close this issue for now.  This functionality is not needed for now.
