### ISSUE TITLE
Versions PUT cmd gets an Internal Server 500 error

### ISSUE THREAD

**Issue by fyangd** [devigned/pub#28]
## What Happened

When I run the following command:

```
az_pub versions put image -p vmware-inc -o tkg-capi -s k8s-1dot18dot14-ubuntu-1804 --version 2021.02.24 --vhd-uri <vhd-url>
```

I get the following internal server 500 error:

```
16:14:48  unable to put offer: uri: https://cloudpartner.azure.com/api/publishers/vmware-inc/offers/tkg-capi?api-version=2017-10-31, status: 500, body: {"Variant":{"serviceName":"Variant","error":"snapshot() resulted in an internal conflict! Retry is OK.\r\n[\r\n  \"azure-sku [variantId: edccc6b4-0e81-4af3-9d08-ada64584105d, configuration.externalId: k8s-1dot17dot11-ubuntu-1804] -- mismatch(1)\",\r\n  \"azure-sku [variantId: 66570f10-77e2-4173-810d-e75661449e05, configuration.externalId: k8s-1dot18dot8-ubuntu-1804] -- mismatch(1)\",\r\n  \"azure-sku [variantId: edb770f9-fb05-44e7-85b6-ff2e14358c35, configuration.externalId: k8s-1dot19dot1-ubuntu-1804] -- mismatch(1)\",\r\n ...
```

## What did you expect
I expect a 200 OK status code

## What have you done to debug the issue

This issue recently started occurring after this command has run successfully for months.  It can be consistently reproduced locally and in our CI environment.

The interesting thing is that querying against the same [marketplace API](https://docs.microsoft.com/en-us/azure/marketplace/cloud-partner-portal-api-creating-offer) using a different client (Postman) with the *same exact* request header and body that I extracted from debugging the client, results in a 200 OK status.  Therefore I have ruled it out to be simply a Marketplace API issue.

I've yet to see if I can reproduce this issue against a smaller offering, but I'll update this issue thread here with my findings.

**Comment by fyangd** [comment]
cc. @devigned @marosset

**Comment by devigned** [comment]
Is this a consistent error or is this periodic?

**Comment by fyangd** [comment]
This is consistent.  In fact, it hasn't succeeded since it started erring out on the 500 status code.

**Comment by devigned** [comment]
Looking at the error, it looks like it's asking the client to retry the `PUT`. I wonder if some order of mutations cause an internal server error that requires the request to be retried. Perhaps, that is why you were successful with your postman synthetic request. WDYT?

**Comment by fyangd** [comment]
Thanks for responding, David.   That could be a possibility, but repeating retrying the put request doesn't succeed either.

Either way, it looks more like a marketplace API issue now, because simple GET requests are resulting in 500 internal server errors:

```
{
    "Submission": {
        "serviceName": "Submission",
        "error": "System.InvalidOperationException: [vmware-inc/tkg-capi] Could not GET stitch response for submission-less draft OfferJson, PC product: 62026110/28f28818-30e5-4c40-a0e7-e6a6075b5515\r\n   at Microsoft.Ingestion.Api.Controllers.CppOperationController.<>c__DisplayClass20_0.<<GetDraftOfferJsonAsync>b__0>d.MoveNext() in E:\\Agent_work\\1\\b\\433\\_work\\1\\s\\src\\Ingestion.Api\\Controllers\\CppShimming\\CppOperationController.Product.cs:line 186",
        "exceptionCode": "InvalidOperationException",
        "httpStatusCode": "InternalServerError"
    }
}
```

I have scheduled a support call with MSFT.

**Comment by devigned** [comment]
Sorry you are running into this, @fyangd. Please let us know if there is anything we can do to help out.

**Comment by fyangd** [comment]
Thanks for checking back, @devigned! I'm in touch with MSFT support, and they have been helpful so far.  Will update here with any resolutions.

**Comment by fyangd** [comment]
Closing this issue.  MSFT marketplace responded, and apparently it was due an incompatibility introduced by new fields.   They have patched that issue and it appears that new APIs will be introduced soon.  While they promised backward compatibility, there is a chance that this client may need to be updated as well.
